"""Added timestamp for posts and comments

Revision ID: 6d2e6befbac6
Revises: 940a517c2004
Create Date: 2025-02-27 01:26:09.958082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2e6befbac6'
down_revision = '940a517c2004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
