"""Added description with word limit in posts

Revision ID: 940a517c2004
Revises: d0945a5765db
Create Date: 2025-02-27 00:11:49.368139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940a517c2004'
down_revision = 'd0945a5765db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
